---
name: dry run
'on':
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm test
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: "unused"
          dryRun: true