# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Compile VS Code Extension
        uses: lannonbr/vsce-action@master
        with:
          args: "package"

      - name: Publish VS Code Extension
        # You may pin to the exact commit or the version.
        # uses: HaaLeo/publish-vscode-extension@837bbbadcc731bdc0e9d09dce7143d3f7f5d4f43
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          # Personal access token
          pat: "${{OPEN_VSX_PAT}}"
          # Set this option to "true" to package your extension but do not publish it.
          dryRun: true
