---
name: CI
'on':
  push:
    branches:
      - main
      - *
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile VS Code Extension
        uses: lannonbr/vsce-action@master
        with:
          args: package
      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{OPEN_VSX_PAT}}
          dryRun: true